// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udeelaurcjiqkdfjjgzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkZWVsYXVyY2ppcWtkZmpqZ3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NzAzNDcsImV4cCI6MjA3NzI0NjM0N30.g-8IvQY1G-uX1FdArL7Wdko7-wvw_VN9Wb3gmy9EYRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});